name: Testes Mínimos do Frontend

# ... (on, jobs, runs-on)

    defaults:
      run:
        working-directory: SafeTempApp

    steps:
      
      - name: Instalar dependências
        run: npm install --legacy-peer-deps

      - name: Rodar Testes
        run: npm run test